services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - gitea_data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=192.168.2.50
      - GITEA__server__ROOT_URL=http://192.168.2.50:3000/
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=sqlite3

volumes:
  gitea_data:
