[Interface]
Address = 10.200.200.2/24
PrivateKey = DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE=

[Peer]
# hub
PublicKey = EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEF=
AllowedIPs = 10.200.200.0/24
Endpoint = 192.168.2.1:51820
PersistentKeepalive = 25
