version: 1

networks:
  - name: internal
    cidr: 192.168.60.0/24

instances:
  - name: monitoring
    hostname: monitoring
    image: ubuntu-22.04
    memory: 2048
    cpus: 2
    disk_size: 30G
    ssh_port: 2226
    ports:
      - "9090:9090"
      - "3000:3000"
    user: ubuntu
    sudo: nopasswd
    networks:
      - name: internal
        ipv4: 192.168.60.10

    provision:
      packages:
        - curl
        - ca-certificates
        - gnupg
      shell:
        - hostnamectl set-hostname monitoring
        - timedatectl set-timezone UTC
        - ufw allow OpenSSH
        - ufw allow 9090
        - ufw allow 3000
        - ufw allow 9100
        - ufw --force enable
        - install -m 0755 -d /etc/apt/keyrings
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        - chmod a+r /etc/apt/keyrings/docker.asc
        - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
        - apt-get update -qq
        - apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
        - usermod -aG docker ubuntu
        - systemctl enable --now docker

  - name: app
    hostname: app
    image: ubuntu-22.04
    memory: 1024
    cpus: 2
    disk_size: 20G
    ssh_port: 2227
    user: ubuntu
    sudo: nopasswd
    networks:
      - name: internal
        ipv4: 192.168.60.20

    provision:
      packages:
        - python3
        - python3-pip
        - curl
      shell:
        - hostnamectl set-hostname app
        - timedatectl set-timezone UTC
        - ufw allow OpenSSH
        - ufw allow 8000
        - ufw allow 9100
        - ufw --force enable
